project:
  type: book
  output-dir: docs
  
book:
  title: "Repositório Inf. Bayseana"
  author: "Daniel Figueira Ferreira"
  date: "9/1/2023"
  chapters:
    - index.qmd
    - part: relatorios.qmd
      chapters: 
        - relatorio1.qmd
        - relatorio2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

